apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.app}}

spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0        # Don't create new pods before killing old ones
      maxUnavailable: 1  # Only take down one pod at a time
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.app}}
  template:
    metadata:
      labels:
        app: {{.Values.app}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "32762"
        checksum/opensips-cfg-configmap: {{ include (print $.Template.BasePath "/opensips-cfg-configmap.yaml") . | sha256sum }}
        checksum/opensips-mrcp-configmap: {{ include (print $.Template.BasePath "/opensips-mrcp-configmap.yaml") . | sha256sum }}
    spec:
      hostNetwork: true
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: {{.Values.app}}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/bash", "-c"]
        args:
          - "envsubst '$NUM_CHILDREN,$LOG_LEVEL,$DEBUG_MODE,$INTERNAL_IP,$DIALOG_TIMEOUT' < /usr/src/opensips-3.6.2/configs/opensips.cfg.template > /usr/src/opensips-3.6.2/configs/opensips.cfg && ./opensips -F -f configs/opensips.cfg -m 512 -M 64"
        # command: ["/bin/bash","-c"]
        # args: [ "sleep 1000000;"]
        resources:
{{ toYaml .Values.resources | indent 12 }}
        env:
          - name: INTERNAL_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: "{{ $value }}"
        {{- end }}
        ports:
        - containerPort: 9060
          hostPort: 9060
          protocol: UDP
          name: "udp-9060"
        - containerPort: 9060
          hostPort: 9060
          protocol: TCP
          name: "tcp-9060"
        - containerPort: 32762
          hostPort: 32762
          protocol: TCP
          name: "tcp-32762"
        {{- if .Values.enableReadinessProbe }}
        readinessProbe:
          tcpSocket:
            port: 9060
          initialDelaySeconds: {{ .Values.readinessProbeInitialDelay }}
          periodSeconds: {{ .Values.readinessProbeInterval }}
          timeoutSeconds: {{ .Values.readinessProbeTimeout }}
        {{- end }}
        {{- if .Values.enableLivenessProbe }}
        livenessProbe:
          tcpSocket:
            port: 9060
          initialDelaySeconds: {{ add .Values.livenessProbeInitialDelay .Values.readinessProbeInitialDelay }}
          periodSeconds: {{ .Values.livenessProbeInterval }}
          timeoutSeconds: {{ .Values.livenessProbeTimeout }}
        {{- end }}
        volumeMounts:
          - name: opensips-mrcp-configmap
            mountPath: /usr/src/opensips-3.6.2/scripts/dbtext/opensips/load_balancer
            subPath: load_balancer
          - name: opensips-cfg-configmap
            mountPath: /usr/src/opensips-3.6.2/configs/opensips.cfg.template
            subPath: opensips.cfg.template
    {{- with .Values.nodeSelector }}
      nodeSelector:
  {{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
  {{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
  {{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: opensips-mrcp-configmap
          configMap:
            name: opensips-mrcp-configmap
        - name: opensips-cfg-configmap
          configMap:
            name: opensips-cfg-configmap
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirstWithHostNet
